### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by irreleph4nt** [saivert/deadbeef-flatpak#2]
Hi and thank you for your work bringing deadbeef to flatpak. I am a new flatpak user on Debian and so far have used only flathub as a repository. How do I go about adding deadbeef so it can be installed via the flatpak application?

**Comment by saivert** [comment]
Did you check the releases on github for this project? I will try to post releases there when new versions of Deadbeef are released.

Furthermore this is a repo for building the Deadbeef flatpak from source. I'm not sure if the project is ready to be hosted on flathub yet. There are some outstanding issues to make it fully ready and I would need help with the remaining bits and also help with how to get it on flathub as I don't know the flathub maintainers.

**Comment by mattstepb** [comment]
>Furthermore this is a repo for building the Deadbeef flatpak from source. I'm not sure if the project is ready to be hosted on flathub yet. There are some outstanding issues to make it fully ready and I would need help with the remaining bits

Maybe you could develop at your own pace like the Lutris ["forever beta"](https://github.com/flathub/net.lutris.Lutris) package. People have to make a conscious decision to add the beta repo. One possible is plugin location, IIRC DeaDBeeF the environment variable only overrides a single location and the app looks at places like ~/.local/lib* for plugins and many people don't like that.

>and also help with how to get it on flathub as I don't know the flathub maintainers.

https://github.com/flathub/flathub/blob/master/CONTRIBUTING.md

You can see how the process works here [github.com/flathub/flathub/issues](https://github.com/flathub/flathub/issues?q=). They do a good review of permissions and possible problems.

Thanks for your work.
